# Generated by Django 2.2 on 2019-11-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191128_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
