# Generated by Django 2.2 on 2019-12-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='images',
            new_name='image',
        ),
    ]
