# Generated by Django 2.2 on 2019-12-03 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191201_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', '-timestamp'], 'permissions': (('can_change_blogpost', 'Can change BlogPost'), ('can_delete_blogpost', 'Can delete BlogPost'))},
        ),
    ]
