# Generated by Django 2.2 on 2019-12-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191203_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'default_permissions': ('add', 'change', 'delete'), 'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
